name: Chris Evans
markdown: kramdown
permalink: /blog/:year/:month/:day/:title


urls:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Projects
    url: /projects/
  - text: Games
    url: /games/
  - text: Gallery
    url: /gallery/
  - text: Blog
    url: /blog/

exclude:
  - "site_mockup.xd"