name: Chris Evans
markdown: kramdown
permalink: /blog/:year/:month/:day/:title


urls:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Projects
    url: /projects/
  - text: Games
    url: /games/
  - text: Gallery
    url: /gallery/
  - text: Blog
    url: /blog/
  - text: Music
    url: /music/

#has to be done this way due to a bug: https://github.com/jekyll/jekyll/issues/1352
include:
  - "_framework"
  - "_bin"

exclude:
  - "site_mockup.xd"
  - "README.md"
  - ".vs"
  - "start.cmd"